export enum AppStates {
  SEQUENCER_STOP = 'STOP',
  SEQUENCER_RECORDING = 'RECORDING',
  SEQUENCER_PLAYING = 'PLAYING',
  SEQUENCER_RECORDING_ARMED = 'RECORDING_ARMED',
  LIBRARY_SAVING_SONG = 'SAVING',
  LIBRARY_LOADING_SONG = 'LOADING'
}
